#!/bin/bash
set -euf -o pipefail

. envs/prod/bin/activate

trap 'kill $(jobs -p)' EXIT

# FIXME: Nope, use yarn
yarn dev &

while true
do
    echo "Starting entr"
    # TODO: add a flag to witchhunt to change log levels, set to DEBUG here
    fd '\.py$' witchhunt/ | entr -dr python -m witchhunt || true
done
