#!/bin/bash
set -euf -o pipefail

. envs/dev/bin/activate

echo "black..."
black witchhunt/

echo ""
echo "flake8..."
flake8 witchhunt/

# TODO: I just expect this to be installed on the system.
echo ""
echo "jslint..."
jshint -c .jshint frontend/prototype.js

echo ""
echo "js-beautify"
js-beautify --replace --end-with-newline frontend/prototype.js
