#!/bin/bash
set -euf -o pipefail

yarn install

python3 -m venv envs/dev
. envs/dev/bin/activate
pip install -r envs/requirements.txt -r envs/requirements-dev.txt
deactivate

python3 -m venv envs/prod
. envs/prod/bin/activate
pip install -r envs/requirements.txt
deactivate
